name: build

on:
  push: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.2
    - name: Run tests
      run: go test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.51.2
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
